# Generated by Django 2.0.5 on 2018-05-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degrees',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planes', verbose_name='Imagen'),
        ),
    ]
