# Generated by Django 2.0.5 on 2018-05-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=25)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=12)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
