# Generated by Django 2.0.4 on 2018-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course', verbose_name='Imagen'),
        ),
    ]
