# Generated by Django 2.0.5 on 2018-05-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180511_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Imagen'),
        ),
    ]
